FORMAT: 1A
HOST: https://njc-school-portal.herokuapp.com

# Portal

Portal that handles student activities in an institution.

# Users Account

A staff/student/accountant can do the following:
1. Create a new account.
2. Login to their account.
3. Get users information.
4. Get access token using the refresh token.
5. Access protected route.

### Admin Registration [/api/v1/auth/staff/register]

#### Register [POST]

+ Request (application/json)

        {
            "firstname": "Peter",
            "lastname": "Gitundu",
            "form": "1",
            "stream": "1A",
            "username": "Peter254",
            "email": "petergitundu44@gmail.com",
            "password": "Peter20930988!"
        }

+ Response 201 (application/json)

    + Body

            {
                  "message": "Account created successfully!",
                  "status": "201",
                  "user": {
                    "created_on": "2020-06-04 22:02:21.406688",
                    "email": "petergitundu44@gmail.com",
                    "firstname": "Peter",
                    "form": "1",
                    "lastname": "Gitundu",
                    "password": "pbkdf2:sha256:150000$XWo2q0vD$5da9ab52bbfdceb1e8e275b1544070e2a43a912a7c67c3f6de8e616652bf7134",
                    "role": "teacher",
                    "stream": "1A",
                    "username": "Peter254"
                  }
            }
            
## Admin Login [/api/v1/auth/staff/login]

### Login [POST]

+ Request (application/json)

        {
            "email": "petergitundu44@gmail.com",
            "password": "Peter20930988!"
        }


+ Response 200 (application/json)

    + Body

            {
                  "message": "Successfully logged in!",
                  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTEyOTc1NjYsIm5iZiI6MTU5MTI5NzU2NiwianRpIjoiZWVmODNiNzUtNDE0NS00NmFiLTg5N2YtN2JjZmMyNGY1ZTYyIiwiZXhwIjoxNjIyODMzNTY2LCJpZGVudGl0eSI6InBldGVyZ2l0dW5kdTQ0QGdtYWlsLmNvbSIsInR5cGUiOiJyZWZyZXNoIn0.c6z17evh1-iV7hJP0EciU9QYvTso16xCusaZSBywPyU",
                  "status": "200",
                  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTEyOTc1NjYsIm5iZiI6MTU5MTI5NzU2NiwianRpIjoiZmNkNGEwYjEtNWZiYS00NmU0LTgxYTgtNmY1MTU2ZTJhOTg4IiwiZXhwIjoxNjIyODMzNTY2LCJpZGVudGl0eSI6InBldGVyZ2l0dW5kdTQ0QGdtYWlsLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.cXQZisV3BQUnEA8WSe4J_pAofYGF804kEU8RUk22fHY",
                  "user": {
                    "created_on": "2020-06-04 22:02:21.406688",
                    "email": "petergitundu44@gmail.com",
                    "firstname": "Peter",
                    "form": "1",
                    "lastname": "Gitundu",
                    "password": "pbkdf2:sha256:150000$XWo2q0vD$5da9ab52bbfdceb1e8e275b1544070e2a43a912a7c67c3f6de8e616652bf7134",
                    "role": "teacher",
                    "staff_id": 1,
                    "stream": "1A",
                    "username": "Peter254"
                  }
            }
            
## Admin Access Token [/api/v1/auth/staff/refresh]

### Get Access Token [POST]

+ Response 200 (application/json)

    + Headers

            Authorization: Bearer Token
            Location: /api/v1/auth/users

    + Body

            {
                "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTEyOTgxODksIm5iZiI6MTU5MTI5ODE4OSwianRpIjoiZmU4MTc2MjctNGQ0My00MzU0LWJhYTAtMjFlY2U3ZmY1YzA4IiwiZXhwIjoxNjIyODM0MTg5LCJpZGVudGl0eSI6InBldGVyZ2l0dW5kdTQ0QGdtYWlsLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.IpGos1gk6V8FZgqvP45w6GBRXQF3gCNAF-tb-o7MxQM"
            }
            
## Admin Protected Route [/api/v1/auth/staff/protected]    
            
### Protected  [GET]

+ Response 200 (application/json)

    + Headers

            Authorization: Bearer Token
            Location: /api/v1/auth/staff/protected
            
    + Body

            {
                "logged_in_as": "petergitundu44@gmail.com"
            }
            
## Admin Get Users [/api/v1/auth/staff/users]    
            
### Get Users  [GET]

+ Response 200 (application/json)

    + Headers

            Authorization: Bearer Token
            Location: /api/v1/auth/staff/users
            
    + Body

            {
                  "message": "success",
                  "status": "200",
                  "users": [
                    {
                      "created_on": "2020-06-04 22:02:21.406688",
                      "email": "petergitundu44@gmail.com",
                      "firstname": "Peter",
                      "form": "1",
                      "lastname": "Gitundu",
                      "password": "pbkdf2:sha256:150000$XWo2q0vD$5da9ab52bbfdceb1e8e275b1544070e2a43a912a7c67c3f6de8e616652bf7134",
                      "role": "teacher",
                      "staff_id": 1,
                      "stream": "1A",
                      "username": "Peter254"
                    }
                  ]
            }
            
            
## Admin Get User By Username [/api/v1/auth/staff/users/{username}]

+ Parameters
    + username (string)

### Get User  [GET]

+ Response 200 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v1/auth/staff/users/{username}
    
    + Body

            {
                  "message": "success",
                  "status": "200",
                  "user": {
                    "created_on": "2020-06-04 22:02:21.406688",
                    "email": "petergitundu44@gmail.com",
                    "firstname": "Peter",
                    "form": "1",
                    "lastname": "Gitundu",
                    "password": "pbkdf2:sha256:150000$XWo2q0vD$5da9ab52bbfdceb1e8e275b1544070e2a43a912a7c67c3f6de8e616652bf7134",
                    "role": "teacher",
                    "staff_id": 1,
                    "stream": "1A",
                    "username": "Peter254"
                  }
            }
            
### Student Register [/api/v1/auth/register]

#### Register [POST]

+ Request (application/json)

        {
            "firstname": "Harun",
            "lastname": "Gachanja",
            "surname": "Gitundu",
            "admission_no": "NJCF1001",
            "gender": "male",
            "email": "arrotechdesign@gmail.com",
            "password": "Harun20930988!",
            "current_year": "1",
            "role": "student"
        }

+ Response 201 (application/json)

    + Body

            {
                  "message": "Account created successfully!",
                  "status": "201",
                  "user": {
                    "admission_no": "NJCF1001",
                    "created_on": "2020-06-04 23:05:16.738564",
                    "current_year": "1",
                    "email": "arrotechdesign@gmail.com",
                    "firstname": "Harun",
                    "gender": "male",
                    "is_confirmed": false,
                    "lastname": "Gachanja",
                    "password": "pbkdf2:sha256:150000$1AEGuLqc$0dfbddb71c7d014c39ccbc3bf0a1c38dffb686c2d95ec6d8a1b86a3288dbaab0",
                    "role": "student",
                    "surname": "Gitundu"
                  }
            }
            
## Student Login [/api/v1/auth/login]

### Login [POST]

+ Request (application/json)

        {
            "email": "arrotechdesign@gmail.com",
            "password": "Harun20930988!"
        }


+ Response 200 (application/json)

    + Body

            {
                  "message": "Successfully logged in!",
                  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTEzMDE3NzQsIm5iZiI6MTU5MTMwMTc3NCwianRpIjoiYWQ3ZjI0MjYtMDMzZi00Y2JhLWJiZmMtMzhmYTZlOWMxMGE2IiwiZXhwIjoxNjIyODM3Nzc0LCJpZGVudGl0eSI6ImFycm90ZWNoZGVzaWduQGdtYWlsLmNvbSIsInR5cGUiOiJyZWZyZXNoIn0.8XudXqTbCns5sZv2tYTusvt6nztIDA2HSECzNPuMfiY",
                  "status": "200",
                  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTEzMDE3NzQsIm5iZiI6MTU5MTMwMTc3NCwianRpIjoiMzVhNTkzYjEtZWM3Yi00NGNjLTg3OTUtYzcyOWVlYTExNmEwIiwiZXhwIjoxNjIyODM3Nzc0LCJpZGVudGl0eSI6ImFycm90ZWNoZGVzaWduQGdtYWlsLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.oj-QLMuVTJ5v-6agdwLafFj0cFYg5Tmi6sGYkdldrSk",
                  "user": {
                    "admission_no": "NJCF1001",
                    "confirmed_on": null,
                    "created_on": "2020-06-04 23:05:16.738564",
                    "current_year": "1",
                    "email": "arrotechdesign@gmail.com",
                    "firstname": "Harun",
                    "gender": "male",
                    "is_confirmed": false,
                    "lastname": "Gachanja",
                    "password": "pbkdf2:sha256:150000$1AEGuLqc$0dfbddb71c7d014c39ccbc3bf0a1c38dffb686c2d95ec6d8a1b86a3288dbaab0",
                    "role": "student",
                    "surname": "Gitundu",
                    "user_id": 1
                  }
            }
            
## Get Student By Registration No. [/api/v1/auth/users/{admission_no}]

+ Parameters
    + admission_no (string)

### Get Student  [GET]

+ Response 200 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v1/auth/users/{admission_no}
    
    + Body

            {
                  "message": "success",
                  "status": "200",
                  "user": {
                    "created_on": "2020-06-04 22:02:21.406688",
                    "email": "petergitundu44@gmail.com",
                    "firstname": "Peter",
                    "form": "1",
                    "lastname": "Gitundu",
                    "password": "pbkdf2:sha256:150000$XWo2q0vD$5da9ab52bbfdceb1e8e275b1544070e2a43a912a7c67c3f6de8e616652bf7134",
                    "role": "teacher",
                    "staff_id": 1,
                    "stream": "1A",
                    "username": "Peter254"
                  }
            }
            
## Add Campus [/api/v1/campuses]

### Add [POST]

+ Request (application/json)

        {
            "campus_name": "main",
            "campus_location": "juja"
        }


+ Response 200 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v1/campuses

    + Body

            {
                  "data": {
                    "campus_location": "juja",
                    "campus_name": "main",
                    "created_on": "Thu, 04 Jun 2020 23:39:28 GMT"
                  },
                  "message": "Campus added successfully",
                  "status": 201
            }
            
## Add Certificate [/api/v1/certificates]

### Add [POST]

+ Request (application/json)

        {
            "certificate_name": "Degree"
        }


+ Response 200 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v1/certificates

    + Body

            {
              "data": {
                "certificate_name": "Degree",
                "created_on": "Thu, 04 Jun 2020 23:59:26 GMT"
              },
              "message": "Certificate added successfully",
              "status": 201
            }
            
## Add Department [/api/v1/departments]

### Add [POST]

+ Request (application/json)

        {
            "department_name": "mathematics"
        }


+ Response 200 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v1/departments

    + Body

            {
              "data": {
                "created_on": "Fri, 05 Jun 2020 00:03:39 GMT",
                "department_name": "mathematics"
              },
              "message": "Department added successfully",
              "status": 201
            }
            
## Add Course [/api/v1/courses]

### Add [POST]

+ Request (application/json)

        {
            "course_name": "maths and computer science",
            "department_name": "mathematics"
        }


+ Response 200 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v1/courses

    + Body

            {
              "data": {
                "course_name": "maths and computer science",
                "created_on": "Fri, 05 Jun 2020 00:08:23 GMT",
                "department": "mathematics"
              },
              "message": "maths and computer science added successfully",
              "status": 201
            }
            
## Add Unit [/api/v1/units]

### Add [POST]

+ Request (application/json)

        {
            "unit_name": "Calculus 1",
            "unit_code": "SMA001"
        }


+ Response 200 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v1/units

    + Body

            {
              "data": {
                "created_on": "Fri, 05 Jun 2020 00:10:46 GMT",
                "unit_code": "SMA001",
                "unit_name": "Calculus 1"
              },
              "message": "Unit added successfully",
              "status": 201
            }
            
## Add Hostel [/api/v1/hostels]

### Add [POST]

+ Request (application/json)

        {
            "hostel_name": "nyati",
            "rooms": "400",
            "gender": "male",
            "hostel_location": "sunrise"
        }


+ Response 200 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v1/hostels

    + Body

            {
              "data": {
                "created_on": "Fri, 05 Jun 2020 00:14:15 GMT",
                "gender": "male",
                "hostel_location": "sunrise",
                "hostel_name": "nyati",
                "rooms": "400"
              },
              "message": "Hostel added successfully",
              "status": 201
            }
            
## Apply Course [/api/v1/apply_course]

### Apply [POST]

+ Request (application/json)

        {
            "admission_no": "NJCF1001",
            "campus_id": "1",
            "certificate_id": "1",
            "department_name": "mathematics",
            "course_name": "maths and computer science"
        }


+ Response 200 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v1/apply_course

    + Body

            {
              "data": {
                "campus": 1,
                "certificate": 1,
                "course": "maths and computer science",
                "created_on": "Fri, 05 Jun 2020 00:20:36 GMT",
                "department": "mathematics",
                "student": "NJCF1001"
              },
              "message": "Course applied successfully",
              "status": 201
            }
            
## Book Hostel [/api/v1/accommodation]

### Book [POST]

+ Request (application/json)

        {
            "admission_no": "NJCF1001",
            "hostel_name": "nyati"
        }


+ Response 200 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v1/accommodation

    + Body

            {
              "data": {
                "created_on": "Fri, 05 Jun 2020 00:25:06 GMT",
                "hostel": "nyati",
                "student": "NJCF1001"
              },
              "message": "Hostel booked successfully",
              "status": 201
            }