FORMAT: 1A
HOST: https://njc-school-portal.herokuapp.com

# Portal

Portal that handles student activities in an institution.

## Staff

### Create Account [/api/v1/auth/staff/register]

#### REGISTER [POST]

+ Request (application/json)

        {
            "firstname": "Peter",
            "lastname": "Gitundu",
            "form": "1",
            "stream": "1A",
            "username": "Peter254",
            "email": "petergitundu44@gmail.com",
            "password": "Peter20930988!"
        }

+ Response 201 (application/json)

    + Body

            {
                  "message": "Account created successfully!",
                  "status": "201",
                  "user": {
                    "created_on": "2020-06-04 22:02:21.406688",
                    "email": "petergitundu44@gmail.com",
                    "firstname": "Peter",
                    "form": "1",
                    "lastname": "Gitundu",
                    "password": "pbkdf2:sha256:150000$XWo2q0vD$5da9ab52bbfdceb1e8e275b1544070e2a43a912a7c67c3f6de8e616652bf7134",
                    "role": "teacher",
                    "stream": "1A",
                    "username": "Peter254"
                  }
            }
            
## Login [/api/v1/auth/staff/login]

### Login [POST]

+ Request (application/json)

        {
            "email": "petergitundu44@gmail.com",
            "password": "Peter20930988!"
        }


+ Response 200 (application/json)

    + Body

            {
                  "message": "Successfully logged in!",
                  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTEyOTc1NjYsIm5iZiI6MTU5MTI5NzU2NiwianRpIjoiZWVmODNiNzUtNDE0NS00NmFiLTg5N2YtN2JjZmMyNGY1ZTYyIiwiZXhwIjoxNjIyODMzNTY2LCJpZGVudGl0eSI6InBldGVyZ2l0dW5kdTQ0QGdtYWlsLmNvbSIsInR5cGUiOiJyZWZyZXNoIn0.c6z17evh1-iV7hJP0EciU9QYvTso16xCusaZSBywPyU",
                  "status": "200",
                  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTEyOTc1NjYsIm5iZiI6MTU5MTI5NzU2NiwianRpIjoiZmNkNGEwYjEtNWZiYS00NmU0LTgxYTgtNmY1MTU2ZTJhOTg4IiwiZXhwIjoxNjIyODMzNTY2LCJpZGVudGl0eSI6InBldGVyZ2l0dW5kdTQ0QGdtYWlsLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.cXQZisV3BQUnEA8WSe4J_pAofYGF804kEU8RUk22fHY",
                  "user": {
                    "created_on": "2020-06-04 22:02:21.406688",
                    "email": "petergitundu44@gmail.com",
                    "firstname": "Peter",
                    "form": "1",
                    "lastname": "Gitundu",
                    "password": "pbkdf2:sha256:150000$XWo2q0vD$5da9ab52bbfdceb1e8e275b1544070e2a43a912a7c67c3f6de8e616652bf7134",
                    "role": "teacher",
                    "staff_id": 1,
                    "stream": "1A",
                    "username": "Peter254"
                  }
            }
            
## Token Refresh [/api/v1/auth/staff/refresh]

### Refresh [POST]

+ Response 200 (application/json)

    + Headers

            Authorization: Bearer Token
            Location: /api/v1/auth/users

    + Body

            {
                "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTEyOTgxODksIm5iZiI6MTU5MTI5ODE4OSwianRpIjoiZmU4MTc2MjctNGQ0My00MzU0LWJhYTAtMjFlY2U3ZmY1YzA4IiwiZXhwIjoxNjIyODM0MTg5LCJpZGVudGl0eSI6InBldGVyZ2l0dW5kdTQ0QGdtYWlsLmNvbSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.IpGos1gk6V8FZgqvP45w6GBRXQF3gCNAF-tb-o7MxQM"
            }
            
## Protected Route [/api/v1/auth/staff/protected]    
            
### Protected  [GET]

+ Response 200 (application/json)

    + Headers

            Authorization: Bearer Token
            Location: /api/v1/auth/staff/protected
            
    + Body

            {
                "logged_in_as": "petergitundu44@gmail.com"
            }
            
## Get all Users [/api/v1/auth/staff/users]    
            
### Get Users  [GET]

+ Response 200 (application/json)

    + Headers

            Authorization: Bearer Token
            Location: /api/v1/auth/staff/users
            
    + Body

            {
                  "message": "success",
                  "status": "200",
                  "users": [
                    {
                      "created_on": "2020-06-04 22:02:21.406688",
                      "email": "petergitundu44@gmail.com",
                      "firstname": "Peter",
                      "form": "1",
                      "lastname": "Gitundu",
                      "password": "pbkdf2:sha256:150000$XWo2q0vD$5da9ab52bbfdceb1e8e275b1544070e2a43a912a7c67c3f6de8e616652bf7134",
                      "role": "teacher",
                      "staff_id": 1,
                      "stream": "1A",
                      "username": "Peter254"
                    }
                  ]
            }
            
            
## Get User By Username [/api/v1/auth/staff/users/{username}]

+ Parameters
    + username (string)

### Get User  [GET]

+ Response 200 (application/json)

    + Headers
    
            Authorization: Bearer Token
            Location: /api/v1/auth/staff/users/{username}
    
    + Body

            {
                  "message": "success",
                  "status": "200",
                  "user": {
                    "created_on": "2020-06-04 22:02:21.406688",
                    "email": "petergitundu44@gmail.com",
                    "firstname": "Peter",
                    "form": "1",
                    "lastname": "Gitundu",
                    "password": "pbkdf2:sha256:150000$XWo2q0vD$5da9ab52bbfdceb1e8e275b1544070e2a43a912a7c67c3f6de8e616652bf7134",
                    "role": "teacher",
                    "staff_id": 1,
                    "stream": "1A",
                    "username": "Peter254"
                  }
            }