"""empty message

Revision ID: 14cd35009dc2
Revises: fcb9ccf58878
Create Date: 2021-01-12 00:28:42.876070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14cd35009dc2'
down_revision = 'fcb9ccf58878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('units')
    op.drop_table('notifications')
    op.drop_table('departments')
    op.drop_table('users')
    op.drop_table('institutions')
    op.drop_table('hostels')
    op.drop_table('academic_year')
    op.drop_table('campuses')
    op.drop_table('courses')
    op.drop_table('certificates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('certificate_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('certificate_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('certificate_id', name='certificates_pkey')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department'], ['departments.department_id'], name='courses_department_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', name='courses_pkey'),
    sa.UniqueConstraint('course_name', name='courses_course_name_key')
    )
    op.create_table('campuses',
    sa.Column('campus_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campus_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('campus_location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('campus_id', name='campuses_pkey')
    )
    op.create_table('academic_year',
    sa.Column('year_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('semester', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('year_id', name='academic_year_pkey')
    )
    op.create_table('hostels',
    sa.Column('hostel_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hostel_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rooms', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hostel_location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('hostel_name', name='hostels_pkey')
    )
    op.create_table('institutions',
    sa.Column('institution_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('institution_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('institution_name', name='institutions_pkey')
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('admission_no', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_confirmed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('confirmed_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('admission_no', name='users_pkey')
    )
    op.create_table('departments',
    sa.Column('department_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('department_id', name='departments_pkey')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('notification_id', name='notifications_pkey')
    )
    op.create_table('units',
    sa.Column('unit_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unit_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('unit_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('unit_name', name='units_pkey')
    )
    # ### end Alembic commands ###
