"""empty message

Revision ID: 23653eb34b40
Revises: 33e37dbe5726
Create Date: 2021-01-26 12:01:53.555758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23653eb34b40'
down_revision = '33e37dbe5726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'marks', sa.Float())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'marks')
    # ### end Alembic commands ###
