"""empty message

Revision ID: 32e6518e2dc4
Revises: 58ce8dcd4e8e
Create Date: 2021-01-25 18:46:38.036645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # noqa

# revision identifiers, used by Alembic.
revision = '32e6518e2dc4'
down_revision = '58ce8dcd4e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('username', sa.VARCHAR(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
