"""empty message

Revision ID: 33e37dbe5726
Revises: 3d7f40944cd6
Create Date: 2021-01-26 11:19:17.080634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # noqa

# revision identifiers, used by Alembic.
revision = '33e37dbe5726'
down_revision = '3d7f40944cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'notifications',
        sa.Column('is_read', sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE notifications SET is_read = False")
    op.alter_column('notifications', 'is_read', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'is_read')
    # ### end Alembic commands ###
