"""empty message

Revision ID: 3d7f40944cd6
Revises: 32e6518e2dc4
Create Date: 2021-01-25 18:55:00.309524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # noqa

# revision identifiers, used by Alembic.
revision = '3d7f40944cd6'
down_revision = '32e6518e2dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'exam_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'exams',
        sa.Column('exam_type', sa.VARCHAR(), nullable=True)
    )
    op.execute("UPDATE exams SET exam_type = 'MAIN'")
    op.alter_column('exams', 'exam_type', nullable=False)