"""empty message

Revision ID: 58ce8dcd4e8e
Revises: a19a1b721ef2
Create Date: 2021-01-25 18:46:03.661005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # noqa

# revision identifiers, used by Alembic.
revision = '58ce8dcd4e8e'
down_revision = 'a19a1b721ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('username', sa.VARCHAR(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
