"""empty message

Revision ID: a19a1b721ef2
Revises: 692c29a21f98
Create Date: 2021-01-25 18:36:38.885241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # noqa

# revision identifiers, used by Alembic.
revision = 'a19a1b721ef2'
down_revision = '692c29a21f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('username', sa.VARCHAR(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
